---
- name: Remove any obsolete scripts used by an old version of the role
  file: path={{ item }} state=absent
  with_items:
    - /etc/network/if-post-down.d/iptables-v4
    - /etc/network/if-pre-up.d/iptables-v4
    - /etc/iptables.v4.saved

- name: Install iptables-persistent
  become: true
  apt: name=iptables-persistent state=present

- name: Check if netfilter-persistent is present
  become: true
  shell: which netfilter-persistent
  register: is_netfilter
  when: v4_script|changed or v6_script|changed
  changed_when: false
  ignore_errors: yes
  check_mode: no

- name: Save rules (netfilter-persistent)
  become: true
  command: netfilter-persistent save
  when: not ansible_check_mode and (v4_script|changed or v6_script|changed) and is_netfilter.rc == 0

- name: Save rules (iptables-persistent)
  become: true
  command: /etc/init.d/iptables-persistent save
  when: not ansible_check_mode and (v4_script|changed or v6_script|changed) and is_netfilter.rc == 1
